spring:
  application:
    name: demo

  datasource:
    url: jdbc:mariadb://10.10.10.100:3306/product
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: trued


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
